### ISSUE TITLE
A note from the user ..

### ISSUE THREAD

**Issue by yarodevuci** [lucacasula91/SnackView#1]
It would be great if you included example into your library and fixed missing images on overview page... 
@lucacasula91

**Comment by lucacasula91** [comment]
Hi Yarodevuci.
Images have been fixed right now. 
I'm working for include the demo project, it will be available soon.

Thanks for the tip.

**Comment by yarodevuci** [comment]
@lucacasula91 Great. Thank you

**Comment by yarodevuci** [comment]
@lucacasula91 any updates on demo project ?
