### ISSUE TITLE
Not in cocoapods

### ISSUE THREAD

**Issue by CavalcanteLeo** [lucacasula91/SnackView#10]
[!] CocoaPods could not find compatible versions for pod "SnackView":
  In Podfile:
    SnackView (~> 1.0.2)

Specs satisfying the `SnackView (~> 1.0.2)` dependency were found, but they required a higher minimum deployment target.

Even on deployment target 12.4

**Comment by lucacasula91** [comment]
CavalcanteLeo, i can't reproduce the issue, i am able to install SnackView 1.0.8 via CocoaPods.

**Comment by lucacasula91** [comment]
Can you send a test project with the evidence of the issue?
