### ISSUE TITLE
what is recommended image resolution size for icons?

### ISSUE THREAD

**Issue by yarodevuci** [lucacasula91/SnackView#2]
@lucacasula91 Can you please recommend  icon size? 
Thank you

**Comment by lucacasula91** [comment]
@yarodevuci The recommended icon size for SVApplicationItem is:
- 40x40 for @1x
- 80x80 for @2x
- 120x120 for @3x

**Comment by yarodevuci** [comment]
@lucacasula91 great! Thanks
